### PR TITLE
Fix for defaultValue with required/optional behavior.

### PR DESCRIPTION
**Pull request by fabienb4**
Previous behavior:
- `{ type: String, defaultValue: "Test", optional: true }` => `defaultValue` is not used.
- `{ type: String, defaultValue: "Test" }` => if field not set on insert, upsert or if `$unset`, throws an error.

New behavior: 
- `{ type: String, defaultValue: "Test", optional: true }` => If field not set, use `defaultValue` when insert, upsert (_when actually insert_). `$unset` allows to remove the field.
- `{ type: String, defaultValue: "Test" }` => If field not set, use `defaultValue` when insert, upsert (_when actually insert_). When `$unset`, replace the `$unset` statement by `$set` with `defaultValue`.

Example ouput using collection2 (I removed the `_id` field from results):

``` javascript
Tests = new Mongo.Collection("tests");

var testSchema = new SimpleSchema({
  name:   { type: String },
  tested: { type: String, defaultValue: "Yes" },
  backup: { type: String, defaultValue: "Yes", optional: true }
});

Tests.attachSchema(testSchema);

Tests.insert({ name: "Abcd" });
// Result: { name: 'Abcd', tested: 'Yes', backup: 'Yes' }

Tests.update({ name: "Efgh" }, { $set: { name: "Efgh" } }, { upsert: true });
// Result: { name: 'Efgh', tested: 'Yes', backup: 'Yes' }

Tests.update({ name: "Efgh" }, { $set: { name: "AAA" } }, { upsert: true });
// Result: { name: 'AAA', tested: 'Yes', backup: 'Yes' }

Tests.update({ name: "Abcd"}, { $set: { name: "BBB" } });
// Result: { name: 'BBB', tested: 'Yes', backup: 'Yes' }

Tests.update({ name: "BBB" }, { $unset: { tested: 1, backup: 1 } });
// Result: { name: 'BBB', tested: 'Yes' }
```

### CODE REVIEW

**Comment by fabienb4** [comment]
The behavior with optional always having a value on insert/upsert could be changed. But I think that if there is a defaultValue, it means optional shouldn't be set anyway? Special use cases?

**Comment by aldeed** [comment]
@fabienb4, generally I think this makes a lot of sense. This would have to be merged and released as a major version update, though, since it's not backwards compatible in several ways. I'll work on merging and releasing when I have some time.

**Comment by fabienb4** [comment]
@aldeed, any idea when this could see the light of day? It would be really nice!

**Comment by fabienb4** [comment]
@aldeed Bump! This would be really useful...

**Comment by derwaldgeist** [comment]
I agree that a defaultValue that has to be set explicitly does not make many any sense at all. Is this really the current behaviour?

**Comment by tcastelli** [comment]
+1

**Pull request closed without merging**
